version: "3.4"

services:
  sql.data:
    image: mcr.microsoft.com/mssql/server

  nosql.data:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management-alpine

  core.api:
    restart: on-failure
    build:
      context: .
      dockerfile: GameBox.Web.API/GameBox.Bootstrap/Dockerfile
    depends_on:
      - sql.data
      - rabbitmq

  node.api:
    build:
      context: .
      dockerfile: GameBox.Web.API/game-box-orders-api/Dockerfile
    depends_on:
      - nosql.data
      - rabbitmq

  web.ui:
    build:
      context: .
      dockerfile: game-box-web-ui/Dockerfile
  
volumes:
  sql-data:
    name: GameBoxCoreSQL

  nosql-data:
    name: OrdersMongo

  web-server-data:
    name: WebServerData
  
  rabbitmq-data:
    name: RabbitMQData