version: "3.4"

services:
  sql.data:
    environment:
      SA_PASSWORD: "Your_password@123"
      ACCEPT_EULA: "Y"
    ports:
      - "5433:1433"
    volumes: 
      - "sql-data:/var/opt/mssql"

  nosql.data:
    ports:
      - "27018:27017"
    volumes: 
      - "nosql-data:/data/mongodb"

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes: 
      - "rabbitmq-data:/data/rabbitmq"

  core.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=tcp:172.17.0.1,5433;Initial Catalog=GameBoxCore;User Id=sa;Password=Your_password@123
    ports:
      - "5000:80"

  node.api:
    ports:
      - "1337:1337"

  web.ui:
    volumes:
      - "web-server-data:/data/webserver"
    ports:
      - "4200:80"