version: "3.7"

services:
  sql.data:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server

  nosql.data:
    container_name: mongo-server
    image: mongo

  rabbitmq:
    container_name: RabbitMQ
    image: rabbitmq:3-management-alpine

  core.api:
    container_name: core-api
    restart: on-failure
    build:
      context: ./Server
      dockerfile: GameBox.Bootstrap/Dockerfile
    depends_on:
      - sql.data
      - rabbitmq
      
  notification.api:
    container_name: notification-api
    restart: on-failure
    build:
      context: ./Server/GameBox.Notification
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq

  scheduler:
    container_name: scheduler
    restart: on-failure
    build:
      context: ./Server/GameBox.Scheduler
      dockerfile: Dockerfile
    depends_on:
      - sql.data
      - rabbitmq

  orders.api:
    container_name: orders-api
    build:
      context: ./Server
      dockerfile: game-box-orders-api/Dockerfile
    depends_on:
      - nosql.data
      - rabbitmq

  admin.ui:
    container_name: admin-ui
    build:
      context: ./Client/GameBox.Admin.UI
      dockerfile: Dockerfile

  web.ui:
    container_name: web-ui
    build:
      context: ./Client/game-box-web-ui
      dockerfile: Dockerfile

networks: 
  gamebox-network:
    name: gamebox-network

volumes:
  sql-data:
    name: GameBoxCoreSQL
  nosql-data:
    name: OrdersMongo
  admin-ui-server-data:
    name: AdminUIServerData
  web-ui-server-data:
    name: WebUIServerData  
  rabbitmq-data:
    name: RabbitMQData
  data-protection:
    name: "DataProtection"