version: '3.4'

services:
  sql.data:
    image: "mcr.microsoft.com/mssql/server"

  nosql.data:
    image: mongo

#  rabbitmq:
#    image: rabbitmq:3-management-alpine

  core.api:
    build:
      context: .
      dockerfile: GameBox.Web.API/GameBox.Api/Dockerfile
    depends_on:
      - sql.data

  node.api:
    build:
      context: .
      dockerfile: GameBox.Web.API/game-box-orders-api/Dockerfile
    depends_on:
      - nosql.data

  web.ui:
    build:
      context: .
      dockerfile: game-box-web-ui/Dockerfile