version: "3.7"

services:
  sql.data:
    environment:
      SA_PASSWORD: "Your_password@123"
      ACCEPT_EULA: "Y"
    ports:
      - "5433:1433"
    networks:
      - gamebox-network
    volumes: 
      - "sql-data:/var/opt/mssql"

  nosql.data:
    ports:
      - "27017:27017"
    networks:
      - gamebox-network
    volumes: 
      - "nosql-data:/data/db"

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - gamebox-network
    volumes: 
      - "rabbitmq-data:/var/lib/rabbitmq"

  core.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sql-server;Database=GameBoxCore;User Id=sa;Password=Your_password@123
    ports:
      - "5000:80"
    networks:
      - gamebox-network
    volumes:
      - data-protection:/root/.aspnet/DataProtection-Keys

  notification.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"
    networks:
      - gamebox-network
    volumes:
      - data-protection:/root/.aspnet/DataProtection-Keys

  scheduler:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sql-server;Database=GameBoxCore;User Id=sa;Password=Your_password@123
    networks:
      - gamebox-network

  orders.api:
    ports:
      - "1337:1337"
    networks:
      - gamebox-network

  admin.ui:
    ports:
      - "5400:80"
    networks:
      - "gamebox-network"
    volumes:
      - "admin-ui-server-data:/data/webserver"

  web.ui:
    ports:
      - "4200:80"
    networks:
      - gamebox-network
    volumes:
      - "web-ui-server-data:/data/webserver"