version: "3.7"

services:
  sql.data:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server

  nosql.data:
    container_name: mongo-server
    image: mongo

  rabbitmq:
    container_name: RabbitMQ
    image: rabbitmq:3-management-alpine

  core.api:
    container_name: core-api
    restart: on-failure
    build:
      context: ./Server
      dockerfile: GameBox.Bootstrap/Dockerfile
    depends_on:
      - sql.data
      - rabbitmq
      
  notification.api:
    container_name: notification-api
    restart: on-failure
    build:
      context: ./Server
      dockerfile: GameBox.Notification/Dockerfile
    depends_on:
      - rabbitmq

  scheduler:
    container_name: scheduler
    restart: on-failure
    build:
      context: ./Server
      dockerfile: GameBox.Scheduler/Dockerfile
    depends_on:
      - sql.data
      - rabbitmq

  orders.api:
    container_name: orders-api
    build:
      context: ./Server
      dockerfile: game-box-orders-api/Dockerfile
    depends_on:
      - nosql.data
      - rabbitmq

  web.ui:
    container_name: web-ui
    build:
      context: ./Client
      dockerfile: game-box-web-ui/Dockerfile

networks: 
  gamebox-network:
    name: gamebox-network

volumes:
  sql-data:
    name: GameBoxCoreSQL
  nosql-data:
    name: OrdersMongo
  web-server-data:
    name: WebServerData  
  rabbitmq-data:
    name: RabbitMQData