version: "3.7"

services:
  games.data:
    container_name: games-database
    image: mcr.microsoft.com/mssql/server

  users.data:
    container_name: users-database
    image: postgres:13.1-alpine

  orders.data:
    container_name: orders-data
    image: mongo

  rabbitmq:
    container_name: rabbit-mq
    image: rabbitmq:3.8.9-management-alpine

  redis:
    container_name: redis-cache
    image: redis:6.0.9-alpine

  games.api:
    container_name: games-api
    restart: on-failure
    build:
      context: ./Server/Games.Service
      dockerfile: GameBox.Bootstrap/Dockerfile
    depends_on:
      - games.data
      - rabbitmq

  users.api:
    container_name: users-api
    restart: on-failure
    build:
      context: ./Server/Users.Service
      dockerfile: User.Api/Dockerfile
    depends_on:
      - users.data

  notification.api:
    container_name: notification-api
    restart: on-failure
    build:
      context: ./Server/GameBox.Notification
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq

  scheduler:
    container_name: scheduler
    restart: on-failure
    build:
      context: ./Server/GameBox.Scheduler
      dockerfile: Dockerfile
    depends_on:
      - games.data
      - rabbitmq
      - redis

  orders.api:
    container_name: orders-api
    build:
      context: ./Server
      dockerfile: game-box-orders-api/Dockerfile
    depends_on:
      - orders.data
      - rabbitmq

  admin.ui:
    container_name: admin-ui
    build:
      context: ./Client/GameBox.Admin.UI
      dockerfile: Dockerfile

  web.ui:
    container_name: web-ui
    build:
      context: ./Client/game-box-web-ui
      dockerfile: Dockerfile

networks: 
  gamebox-network:
    name: gamebox-network

volumes:
  games-data:
    name: GamesData
  users-data:
    name: UsersData
  orders-data:
    name: OrdersData
  redis-data:
    name: RedisCacheData
  admin-ui-server-data:
    name: AdminUIServerData
  web-ui-server-data:
    name: WebUIServerData  
  rabbitmq-data:
    name: RabbitMQData
  data-protection:
    name: "DataProtection"