version: "3.7"

services:
  sql.data:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server

  nosql.data:
    container_name: mongoserver
    image: mongo

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine

  core.api:
    container_name: coreapi
    restart: on-failure
    build:
      context: ./GameBox.Web.API
      dockerfile: GameBox.Bootstrap/Dockerfile
    depends_on:
      - sql.data
      - rabbitmq
      
  notification.api:
    container_name: notificationapi
    restart: on-failure
    build:
      context: ./GameBox.Web.API
      dockerfile: GameBox.Notification/Dockerfile
    depends_on:
      - rabbitmq

  orders.api:
    container_name: ordersapi
    build:
      context: ./GameBox.Web.API
      dockerfile: game-box-orders-api/Dockerfile
    depends_on:
      - nosql.data
      - rabbitmq

  web.ui:
    container_name: webui
    build:
      context: .
      dockerfile: game-box-web-ui/Dockerfile

networks: 
  gamebox-network:
    name: gamebox-network
  
volumes:
  sql-data:
    name: GameBoxCoreSQL

  nosql-data:
    name: OrdersMongo

  web-server-data:
    name: WebServerData
  
  rabbitmq-data:
    name: RabbitMQData