version: "3.7"

services:
  games.data:
    environment:
      SA_PASSWORD: "Your_password@123"
      ACCEPT_EULA: "Y"
    ports:
      - "5433:1433"
    networks:
      - gamebox-network
    volumes: 
      - "games-data:/var/opt/mssql"

  users.data:
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: my_secret_password@123
    ports:
      - "5432:5432"
    networks:
      - gamebox-network
    volumes:
      - "users-data:/var/lib/postgresql/data"

  orders.data:
    ports:
      - "27017:27017"
    networks:
      - gamebox-network
    volumes:
      - "orders-data:/data/db"

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - gamebox-network
    volumes: 
      - "rabbitmq-data:/var/lib/rabbitmq"

  redis:
    ports:
      - "6379:6379"
    networks:
      - gamebox-network
    volumes: 
      - "redis-data:/data"

  games.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=172.17.0.1:6379
      - ConnectionStrings__Database=Server=games-database;Database=GameBoxCore;User Id=sa;Password=Your_password@123
    ports:
      - "5000:80"
    networks:
      - gamebox-network
    volumes:
      - data-protection:/root/.aspnet/DataProtection-Keys

  users.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=Server=users-database;Database=UsersCore;User Id=admin;Password=my_secret_password@123
    ports:
      - "5001:80"
    networks:
      - gamebox-network
    volumes:
      - data-protection:/root/.aspnet/DataProtection-Keys

  notification.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:80"
    networks:
      - gamebox-network
    volumes:
      - data-protection:/root/.aspnet/DataProtection-Keys

  scheduler:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=172.17.0.1:6379
      - ConnectionStrings__Database=Server=games-database;Database=GameBoxCore;User Id=sa;Password=Your_password@123
    networks:
      - gamebox-network

  orders.api:
    ports:
      - "1337:1337"
    networks:
      - gamebox-network

  admin.ui:
    ports:
      - "5400:80"
    networks:
      - "gamebox-network"
    volumes:
      - "admin-ui-server-data:/data/webserver"

  web.ui:
    ports:
      - "4200:80"
    networks:
      - gamebox-network
    volumes:
      - "web-ui-server-data:/data/webserver"