version: "3.9"

services:
  messages.data:
    environment:
      SA_PASSWORD: "Your_password@123"
      ACCEPT_EULA: "Y"
    ports:
      - "5434:1433"
    networks:
      - gamebox-network
    volumes: 
      - "messages-data:/var/opt/mssql"

  games.data:
    environment:
      SA_PASSWORD: "Your_password@123"
      ACCEPT_EULA: "Y"
    ports:
      - "5433:1433"
    networks:
      - gamebox-network
    volumes: 
      - "games-data:/var/opt/mssql"

  users.data:
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: my_secret_password@123
    ports:
      - "5432:5432"
    networks:
      - gamebox-network
    volumes:
      - "users-data:/var/lib/postgresql/data"

  orders.data:
    ports:
      - "27017:27017"
    networks:
      - gamebox-network
    volumes:
      - "orders-data:/data/db"

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - gamebox-network
    volumes: 
      - "rabbitmq-data:/var/lib/rabbitmq"

  redis:
    ports:
      - "6379:6379"
    networks:
      - gamebox-network
    volumes: 
      - "redis-data:/data"

  games.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=cert_password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__Redis=172.17.0.1:6379
      - ConnectionStrings__Games=Server=games-database;Database=GamesCore;User Id=sa;Password=Your_password@123;TrustServerCertificate=true
      - ConnectionStrings__Messages=Server=messages-database;Database=MessagesCore;User Id=sa;Password=Your_password@123;TrustServerCertificate=true
      - RabbitMQ__Host=172.17.0.1
      - RabbitMQ__Port=5672
      - RabbitMQ__Usernamet=guest
      - RabbitMQ__Password=guest
    ports:
      - "5000:80"
      - "6000:443"
    networks:
      - gamebox-network
    volumes:
      - ~/.aspnet/https:/https:ro
      - data-protection:/root/.aspnet/DataProtection-Keys

  users.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=cert_password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__Users=Server=users-database;Database=UsersCore;User Id=admin;Password=my_secret_password@123
      - ConnectionStrings__Messages=Server=messages-database;Database=MessagesCore;User Id=sa;Password=Your_password@123;TrustServerCertificate=true
      - RabbitMQ__Host=172.17.0.1
      - RabbitMQ__Port=5672
      - RabbitMQ__Usernamet=guest
      - RabbitMQ__Password=guest
    ports:
      - "5001:80"
      - "6001:443"
    networks:
      - gamebox-network
    volumes:
      - ~/.aspnet/https:/https:ro
      - data-protection:/root/.aspnet/DataProtection-Keys

  notification.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=172.17.0.1
      - RabbitMQ__Port=5672
      - RabbitMQ__Usernamet=guest
      - RabbitMQ__Password=guest
    ports:
      - "5002:80"
    networks:
      - gamebox-network
    volumes:
      - data-protection:/root/.aspnet/DataProtection-Keys

  scheduler:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=172.17.0.1:6379
      - ConnectionStrings__Games=Server=games-database;Database=GamesCore;User Id=sa;Password=Your_password@123;TrustServerCertificate=true
      - ConnectionStrings__Messages=Server=messages-database;Database=MessagesCore;User Id=sa;Password=Your_password@123;TrustServerCertificate=true
      - RabbitMQ__Host=172.17.0.1
      - RabbitMQ__Port=5672
      - RabbitMQ__Usernamet=guest
      - RabbitMQ__Password=guest
    networks:
      - gamebox-network

  orders.api:
    ports:
      - "1337:1337"
    networks:
      - gamebox-network

  admin.ui:
    ports:
      - "5400:80"
    networks:
      - "gamebox-network"
    volumes:
      - "admin-ui-server-data:/data/webserver"

  web.ui:
    ports:
      - "4200:80"
    networks:
      - gamebox-network
    volumes:
      - "web-ui-server-data:/data/webserver"