include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    unnecessary_this: false
    prefer_single_quotes: true
    prefer_const_constructors: false
    avoid_unnecessary_containers: false
    use_key_in_widget_constructors: false
    prefer_const_literals_to_create_immutables: false
